name: powerdart
description: >-
  Updated version of Lorenzo Calisti's powerdart
  Compute the Power Spectral Density (PSD) on Dart.
  This package runs everywhere dart runs.
version: 0.0.3
authors:
  - Lorenzo Calisti <l.calisti96@gmail.com>
homepage: https://github.com/kdomonkosDefIT/powerdart
repository: https://github.com/kdomonkosDefIT/powerdart
issue_tracker: https://github.com/kdomonkosDefIT/powerdart/issues

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  # Dependency for complex numbers
  complex: ^0.7.2

dev_dependencies:
  test: ^1.14.3